language: scala

dist: trusty
sudo: required

jdk:
  - oraclejdk8

scala:
   - 2.12.1

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.nvm

env:
  - TRAVIS_NODE_VERSION="4"

before_install:
  - gem install compass
  - nvm install node
  - npm install -g phantomjs-prebuilt

script:
  - scripts/travis-build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
