language: scala

dist: trusty
sudo: required

jdk:
  - oraclejdk8

scala:
   - 2.12.10

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier/v1
    - $HOME/.nvm

env:
  - TRAVIS_NODE_VERSION="4"

before_install:
  - scripts/travis-setup.sh

script:
  - scripts/travis-build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
