sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

jdk:
  - oraclejdk8

scala:
   - 2.11.7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt coverageAggregate
after_success:
  - sbt coveralls

branches:
 only:
   - master
   - cron-support