sudo: false

language: scala

jdk:
  - oraclejdk8

scala:
   - 2.11.8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

before_install:
  - pip install --user codecov
  - gem install compass

script:
  #- sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION clean test

after_success:
  - codecov
#  - sbt coveralls

branches:
  only:
    - master
