language: scala

jdk:
  - oraclejdk8

scala:
   - 2.11.8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

before_install:
  - gem install compass
  - npm install jsdom

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt coverageReport && sbt coverageAggregate
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
