version: '2'
services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
      - 7000:7000
      - 9160:9160

  master1:
    image: quckoo/master<localBuild>
    ports:
      - 8095:8095
      - 25520:25520
    links:
      - cassandra
    volumes:
      - ./etc/quckoo:/opt/quckoo/conf
    command: --seed --cs cassandra:9042 -b master1:25520

  master2:
    image: quckoo/master<localBuild>
    ports:
      - 8096:8095
      - 25521:25520
    links:
      - cassandra
      - master1
    volumes:
      - ./etc/quckoo:/opt/quckoo/conf
    command: --nodes master1:25520 --cs cassandra:9042 -b master2:25521

  worker:
    image: quckoo/worker<localBuild>
    ports:
      - 50010:50010
    links:
      - master1
      - master2
    volumes:
      - ./etc/quckoo:/opt/quckoo/conf
    command: --master master1:25520,master2:25520 -b worker:50010
