version: '2'
services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
      - 7000:7000
      - 9160:9160

  master:
    image: quckoo/master<localBuild>
    ports:
      - 8095:8095
      - 2551:2551
    links:
      - cassandra
    volumes:
      - ./etc/quckoo:/opt/quckoo/conf
    command: --seed --cs cassandra:9042 -b master:2551

  worker:
    image: quckoo/worker<localBuild>
    ports:
      - 5001:5001
    links:
      - master
    volumes:
      - ./etc/quckoo:/opt/quckoo/conf
    command: --master master:2551
